### ISSUE TITLE
Hello, on which video card or processor should I install MagicTime: slow-motion video generation models like metamorphic simulators, please answer.

### ISSUE THREAD

**Issue by eeeee112** [truedat101/expresscpp#2]
Hello, on which video card or processor should I install MagicTime: slow-motion video generation models
like metamorphic simulators, please answer.

**Comment by truedat101** [comment]
Uh. move this over to https://github.com/PKU-YuanGroup/MagicTime/issues

The answer is: you need 16GB VRAM , Nvidida 30x or 40x if this is a home system.
